package com.example.simplespringbootapp.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Todo extends TodoKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.start
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    private Date start;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.end
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    private Date end;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.title
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.description
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.priority
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table todo
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.start
     *
     * @return the value of todo.start
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public Todo withStart(Date start) {
        this.setStart(start);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.start
     *
     * @param start the value for todo.start
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.end
     *
     * @return the value of todo.end
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public Date getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public Todo withEnd(Date end) {
        this.setEnd(end);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.end
     *
     * @param end the value for todo.end
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public void setEnd(Date end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.title
     *
     * @return the value of todo.title
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public Todo withTitle(String title) {
        this.setTitle(title);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.title
     *
     * @param title the value for todo.title
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.description
     *
     * @return the value of todo.description
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public Todo withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.description
     *
     * @param description the value for todo.description
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.priority
     *
     * @return the value of todo.priority
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public Todo withPriority(Integer priority) {
        this.setPriority(priority);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.priority
     *
     * @param priority the value for todo.priority
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
}