package com.example.simplespringbootapp.domain.model;

import java.io.Serializable;

public class TodoKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.id
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.user_id
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table todo
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.id
     *
     * @return the value of todo.id
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public TodoKey withId(String id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.id
     *
     * @param id the value for todo.id
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.user_id
     *
     * @return the value of todo.user_id
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public TodoKey withUserId(String userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.user_id
     *
     * @param userId the value for todo.user_id
     *
     * @mbg.generated Mon Nov 05 03:10:08 JST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}